
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const QuestionType = {
  SINGLE: 'SINGLE',
  MULTIPLE: 'MULTIPLE',
  TRUE_FALSE: 'TRUE_FALSE',
  TEXT: 'TEXT'
} as const

export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType]


export const Difficulty = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD'
} as const

export type Difficulty = (typeof Difficulty)[keyof typeof Difficulty]


export const QuestionStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const

export type QuestionStatus = (typeof QuestionStatus)[keyof typeof QuestionStatus]


export const ProcessingStatus = {
  UPLOADING: 'UPLOADING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type ProcessingStatus = (typeof ProcessingStatus)[keyof typeof ProcessingStatus]
